source 'https://rubygems.org'

gem 'multi_json'
gem 'rspec'
gem 'dotenv'
gem 'mongo'
gem 'moped'
gem 'traject'
gem 'ecmangle', :git => 'https://github.com/Hathitrust/feddocs_ecmangle.git'
gem 'registry', :git => 'https://github.com/Hathitrust/feddocs_registry.git'
gem 'normalize', :git => 'https://github.com/Hathitrust/feddocs_normalize.git'
gem 'filter', :git => 'https://github.com/Hathitrust/feddocs_filter.git'
gem 'nauth', :git => 'https://github.com/Hathitrust/feddocs_nauth.git'
gem 'oclc_authoritative', :git => 'https://github.com/Hathitrust/feddocs_oclc_authoritative.git'
gem 'google-api-client', '0.11.2'

gem 'rubyzip'
gem 'rake'

gem 'htmlentities'
