source 'https://rubygems.org'

gem 'multi_json'
gem 'rspec'
gem 'dotenv'
gem 'mongo'
gem 'moped'
gem 'traject'
gem 'ecmangle', :git => 'https://github.com/HTGovdocs/ecmangle.git'
gem 'registry', :git => 'https://github.com/HTGovdocs/registry.git'
gem 'normalize', :git => 'https://github.com/HTGovdocs/normalize.git'
gem 'viaf', :git => 'https://github.com/HTGovdocs/viaf.git'
gem 'filter', :git => 'https://github.com/HTGovdocs/filter.git'
gem 'nauth', :git => 'https://github.com/HTGovdocs/nauth.git'
gem 'oclc_authoritative', :git => 'https://github.com/HTGovdocs/oclc_authoritative.git'
gem 'google-api-client', '0.11.2'

gem 'rubyzip'
gem 'rake'

gem 'htmlentities'
